[package]
name = "snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
sysinfo = "0.32.1"

[dependencies.sdl2]
version = "0.35"
default-features = false
features = ["ttf"]